name: Python CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
        env:
          MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
          RUN_RABBITMQ: "False"
      - name: Deploy to Heroku
        run: |
          heroku git:remote -a hhcweather
          git push heroku main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
